name: smart_duel_disk
description: A Smart Duel Disk app for playing Yu-Gi-Oh!.
version: 0.9.0+90000

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.3.2
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.2
  cupertino_icons: ^1.0.3
  dart_twitter_api: ^0.5.3
  dio: ^4.0.0
  easy_localization: ^3.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.0
  flutter_svg: ^0.22.0
  flutter_widget_from_html_core: ^0.7.0
  font_awesome_flutter: ^9.1.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  html_unescape: ^2.0.0
  injectable: ^1.5.0
  intersperse: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.1.0
  logger: ^1.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^6.0.0
  retrofit: ^2.0.1
  rxdart: ^0.27.2
  shared_preferences: ^2.0.7
  socket_io_client: ^1.0.1
  universal_io: ^2.0.4
  url_launcher: ^6.0.10
  url_strategy: ^0.2.0

dev_dependencies:
  auto_localized_generator: ^1.0.1
  auto_route_generator: ^2.1.0
  build_runner: ^2.1.2
  flutter_gen_runner: ^3.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4
  lint: ^1.7.2
  mockito: ^5.0.15
  retrofit_generator: ^2.0.1

flutter_gen:
  output: lib/generated/
  line_length: 120

flutter:
  uses-material-design: true

  assets:
    - secrets.env
    - assets/illustrations/
    - assets/illustrations/duelists/
    - assets/icons/
    - assets/html/

scripts:
  clean: flutter clean
  deps: flutter pub get
  go: flutter run
  gopro: flutter run --profile
  gorel: flutter run --release
  mac: flutter run -d macos
  web: flutter run -d chrome -t lib/main_web.dart
  all: flutter run -d all
  loco: bundle exec fastlane download_loco_changes
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
